name: finvest_credit_card_account
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  provider: ^6.1.2
  get_it: ^8.0.2
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wells_fargo_logo.png
    - assets/wells_fargo_logo.png
    - assets/citi_logo.png
    - assets/ikea_logo.png
    - assets/category_food_logo.png
    - assets/category_apps_software_logo.png
    - assets/category_health_logo.png
    - assets/jbl_logo.png
    - assets/mcd_logo.png
    - assets/uber_logo.png
    - assets/starbucks_logo.png

  fonts:
    - family: Maison Neue
      fonts:
        - asset: fonts/MaisonNeue-Book.ttf
          weight: 400
        - asset: fonts/MaisonNeue-Medium.ttf
          weight: 500
        - asset: fonts/MaisonNeue-Demi.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
